#!/bin/sh
export ARCH=arm64
export CROSS_COMPILE=/home/chanz22/tc/clang+llvm-12.0.1-aarch64-linux-gnu/bin/llvm-
export CLANG_DIR=/home/chanz22/tc/clang+llvm-12.0.1-aarch64-linux-gnu/bin/clang-12
export LLVM_DIR=/home/chanz22/tc/clang+llvm-12.0.1-aarch64-linux-gnu/bin/llvm-

mkdir temp

  cp -f arch/arm64/configs/chanz_r11s_defconfig .config
  make oldconfig

  TIMESTAMP=$(date +%s)

  make CC="$CLANG_DIR" CROSS_COMPILE="$CROSS_COMPILE" LLVM="$LLVM_DIR"-j$(grep -c ^processor /proc/cpuinfo)

  TIMESTAMP2=$(date +%s)

  echo "compile time:" $(($TIMESTAMP2 - $TIMESTAMP)) "seconds"

echo "compilation done.."
echo ""
echo "now generating boot image.."
echo ""
cd /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/AIK
echo "cleaning up AIK dir.."
./cleanup.sh --nosudo
echo "clean done.."
echo ""
echo "unpacking stock boot.img"
./unpackimg.sh --nosudo
echo "unpack done.."
echo ""
echo "doing some tasks.."

cd /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/AIK/split_img

rm -rf boot.img-kernel

cd /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/out

cp Image /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/temp
cp dtb.img /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/temp

cd /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/temp
echo "task done.."
echo ""
echo "moving kernel image to AIK.."
echo ""
mv Image boot.img-kernel
mv dtb.img boot.img-dtb
cp boot.img-kernel /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/AIK/split_img
cp boot.img-dtb /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/AIK/split_img

cd /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/AIK

echo "now repacking boot with new kernel.."

./repackimg.sh --nosudo

cd ../
rm -rf temp
make mrproper
cd /home/chanz22/Documentos/GitHub/android_kernel_samsung_sdk-s5e9925_r11s/arch64/boot/dts/samsung/r11s
rm -rf *.dtbo.reverse.dts *.dtbo *.dtbo.dtout
cd ../../exynos
rm-rf *.dtb.dtout *.dtb.reverse.dts
echo "..............."
echo "done..!"
